### ISSUE TITLE
Godot 4?

### ISSUE THREAD

**Issue by tavurth** [gilzoide/godot-dispatch-queue#3]
Any chance you'd be interested in an upgrade?

**Comment by tavurth** [comment]
Oh ok I see that this does everything needed anyway 👍 

https://docs.godotengine.org/en/stable/classes/class_workerthreadpool.html

**Comment by tavurth** [comment]
Hmm, they don't really cut it sadly :(

**Comment by gilzoide** [comment]
Well, shouldn't be too hard, the refactor for supporting Godot 4 should be simple enough.

> Oh ok I see that this does everything needed anyway 👍

For fire-and-forget tasks, Godot 4's WorkerThreadPool is perfect. I don't know if there is a good way for handling continuations on the tasks dispatched to it, like this addon provides 🤔

**Comment by gilzoide** [comment]
Alright, Godot 4 support is done! The teste scene embedded in the project seems to be working flawlessly.
The `main` branch is now with the updated code, feel free to use it. I still need to upload a new asset to the Asset Library with it, but I won't look into it it right now.
I'm closing this issue, but feel free to open more issues if you find anything.

Cheers \o/

**Comment by tavurth** [comment]
Wow thank you so much for the prompt response and PR ❤️ 

I will try this out and make some suggestions & PRs if I find bugs!
