### ISSUE TITLE
Create new asset in Asset Library for Dispatch Queue with Godot 4 support

### ISSUE THREAD

**Issue by gilzoide** [gilzoide/godot-dispatch-queue#6]

**Comment by tavurth** [comment]
Hmm I'm also running into similar problems as before for some reason:

```log
E 0:00:07:0282   dispatch_queue.gd:90 @ execute(): Error calling from signal 'finished' to callable: 'StaticBody3D::_generated_chunk': Method expected 0 arguments, but called with 1.
  <C++ Source>   core/object/object.cpp:1140 @ emit_signalp()
  <Stack Trace>  dispatch_queue.gd:90 @ execute()
                 dispatch_queue.gd:253 @ _run_loop()
```
<img width="1031" alt="Screenshot 2024-02-11 at 14 51 31" src="https://github.com/gilzoide/godot-dispatch-queue/assets/100964/5b02a317-2e46-4fc9-a2a1-61e0df9a3194">


<img width="400" alt="Screenshot 2024-02-11 at 14 51 42" src="https://github.com/gilzoide/godot-dispatch-queue/assets/100964/04a34377-72b9-4dec-a195-7e1ad2809952">


For some reason Godot no longer allows signals to be emitted from Threads 🤔

**Comment by tavurth** [comment]
For now this code I wrote will fill my use case, but has to be added as a child to work:

https://gist.github.com/tavurth/f3d93b428e5ea4b15d9b7566581e10b4

So basically waiting until the thread is finished (on the main thread) in _physics_process to emit signals.

**Comment by gilzoide** [comment]
Hi @tavurth.

> Error calling from signal 'finished' to callable: 'StaticBody3D::_generated_chunk': Method expected 0 arguments, but called with 1

It seems the method you hooked into the `finished` signal breaks if you pass arguments to it. I guess if you connect a method that accepts the argument, even if just ignoring it, it should work fine.

**Comment by gilzoide** [comment]
By the way, this issue is about creating a new asset in the Asset Store.
If you want to further discuss this problem you arised, I'll ask you to create a new Issue or Discussion for it, to avoid discussions out of the issue's topic.

**Comment by tavurth** [comment]
> Hi @tavurth.
> 
> > Error calling from signal 'finished' to callable: 'StaticBody3D::_generated_chunk': Method expected 0 arguments, but called with 1
> 
> It seems the method you hooked into the `finished` signal breaks if you pass arguments to it. I guess if you connect a method that accepts the argument, even if just ignoring it, it should work fine.

Wow I must be needing sleep more than I thought 😅 I didn't notice that and assumed it was another issue!
